rewe_url: https://www.rewe.de/angebote/dettingen/865862/rewe-markt-kirchheimer-str-138
webhook_url: https://discord.com/api/webhooks/972829351575945236/oOaMrI2tFaI0OSht2ns6wH7x80rdXyODt846EPgGCbfv0Yn3OcULGLwUGxFr9N_d2b_6

ignore: [
  "Topangebote",
  "Auf in die Spargelsaison", 
  "Obst & Gemüse", 
  "PAYBACK Punkte Highlights",
  "Frische & Convenience",
  "Frühstück",
  "Kochen & Backen",
  "Haushalt",
  "Drogerie",
  "Tier",
  "Freizeit & Mode"
  ]
